### PR TITLE
[Android] Update gitignore

### PR DESCRIPTION
**Pull request by gujjwal00**
Updates gitignore file to exclude temporary/local files.

I also want to ignore `.idea` directory but skipped it as it is already in the tree. Maybe we can ignore specific files & directories inside `.idea`.

### CODE REVIEW

**Comment by gujjwal00** [comment]
@bk138 what do you think about ignoring `.idea` directory?

**Comment by bk138** [comment]
Does not seem overly important to me. What do the official guidelines say?

**Comment by gujjwal00** [comment]
It is important because Android studio generates a lot of temporary files in that directory and we have to avoid them on every commit.

Here is the .gitignore file of brand new Android Studio project:
```
*.iml
.gradle
/local.properties
/.idea/caches
/.idea/libraries
/.idea/modules.xml
/.idea/workspace.xml
/.idea/navEditor.xml
/.idea/assetWizardSettings.xml
.DS_Store
/build
/captures
.externalNativeBuild
.cxx

``` 

See: https://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project

**Comment by bk138** [comment]
OK with me :-)

**Pull request merged**
