### PR TITLE
Android: Integrate native LibVNCClient

### PR DESCRIPTION
**Pull request by gujjwal00**
This PR adds more support for native LibVNCClient.

There are some issues but I was so excited about this and couldn't wait (sorry 🤠).
Also, I wanted to get your feedback about it.

**PR Summary**

- Created a `NativeRfbClient` which is a wrapper around native `rfbClient`.
- Use `NativeRfbClient` for VNC connection instead of current `RFBProto`
- Added support for rendering native frame buffer.

What works:
- Frame rendering with OpenGL
- Mouse events
- Keyboard events (Only tested with 'Send Key Combo' dialog, should work with hardware keyboard)
- Authentication 
     1. VncAuth
     2. Few others should work but I need to test them. 
- Clipboard Copy/Paste

**Notes:**
- I have tried to not modify existing native methods created by you. I wanted to get your feedback before that.
- I am testing with Vino server on Ubuntu.
- This PR targets `android-native-libvncclient-4` which is currently behind `master`.
- A lot of error handling is missing.

### CODE REVIEW

**Comment by gujjwal00** [comment]
Marking it as WIP.

**Comment by bk138** [comment]
Yeah you definitely took over the fun part ;-). Anyway, will review ASAP, time permitting.

**Comment by gujjwal00** [comment]
@bk138 Should I implement support for different pixel formats? Currently 24 bit color is supported.

**Comment by bk138** [comment]
> @bk138 Should I implement support for different pixel formats? Currently 24 bit color is supported.

I deem https://github.com/LibVNC/libvncserver/issues/347 more important as it renders viewers useless for users in certain cases (vino + gnutls >= 3.6 I suspect).

**Comment by gujjwal00** [comment]
I was only asking about allowing user to choose different pixel formats with native rfbClient like we currently do. Your comment in `vncconn.c` made me think that we will only support 4 byte-per-pixel with LibVNCClient.


I will pause work on this PR untill your initial review and  focus on the TLS issue for now.

**Comment by gujjwal00** [comment]
This is ready for now. Further work will depend on the feedback.

**Comment by bk138** [comment]
I've now taken a different approach with 62c2cc66280b1724a750d76d8b235c47d0f416fb, the work in here was nevertheless very helpful, thanks a lot @gujjwal00 !

**Comment by gujjwal00** [comment]
No problem! Happy to see it land.

One suggestion I have is to initialize rfbClient pointer in constructor of VNCConn. That way you can drop many null pointer checks.

**Pull request closed without merging**
