### PR TITLE
Android: Add support for night mode (dark theme)

### LINKED ISSUE #142: Add a Dark theme
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Is your feature request about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android): mobile 
 - If Mobile, installed from Play Store or F-Droid: fdroid

**Is your feature request related to a problem? Please describe.**

The regular theme hurts my eyes and doesn't match my system theme
**Describe the solution you'd like**

Add a dark theme with optional automatic system wide detection
**Describe alternatives you've considered**

None
**Additional context**

N/A

### PR DESCRIPTION
**Pull request by gujjwal00**
This adds basic night mode support. If system is in night mode, we will automatically use dark theme.

Fixes #142

### CODE REVIEW

**Comment by bk138** [comment]
@gujjwal00 There's a small issue with this: with bright mode, AlertDialog buttons now have white text on white background. What do you think would be the best solution - adding a specific AlertDialog theme (I tried that for a few minutes, but did not succeed quickly) or adding specific day/night button text colours (did not try that yet...)

**Comment by gujjwal00** [comment]
IMO instead of the modifying the global `android:buttonStyle` we should apply the style directly on the required buttons. I think there are only 5-6 buttons which we want to modify (2 in main activity + 2 in editor activity + 1 in meta-key dialog ...). 

Adding specific day/night button text colors will probably run into the same issue as we want some of the buttons to have white color and other to have primary green color. (I fixed the text color to white because black text on our primary color has poor contrast).

About the issue:
Dialog buttons seems to apply the style from `android:buttonBarButtonStyle` attribute, which is initialized with `android:buttonStyle` attribute. That's why it is inheriting the white text, and probably why setting a AlertDialog theme didn't work.
It also seems to affect API 23+ only.

**Comment by bk138** [comment]
Got it in 89f648e5d4440e03471c7c11c14a47527e96e55d. Not really fun dealing with all those prefixed vs non-prefixed style names though ;-)

**Comment by gujjwal00** [comment]
Yeah, it's like shooting in the dark, except you also have to find the gun first.

**Pull request merged**
