### PR TITLE
[Android] Resize contents on VncCanvasActivity when soft keyboard is visible.

### PR DESCRIPTION
**Pull request by gujjwal00**
Related Issue: #76 

I am assuming that we don't want to remove fullscreen mode. However, if we can afford non-fullscreen mode **OR** immersive (sticky) mode, we might be able to implement a better solution.

Also, given that this is more of a hack, it would be better to get some user experience.

### CODE REVIEW

**Comment by bk138** [comment]
Me thinks we _are_ using immersive (sticky) mode: https://github.com/bk138/multivnc/blob/4a3b3ad51ec24ff7f8dd1f6f143f4119e7dd3a9e/android/app/src/main/java/com/coboltforge/dontmind/multivnc/VncCanvasActivity.java#L1249. IIRC, 018c099cc72c7ad99df7dd12f7cd5b396807c839 was added because I was testing with tablets and the former experience wasn't so nice.

**Comment by bk138** [comment]
Some thoughts:

* I like this PR, it definitely is an improvement over the former behaviour.
* Maybe the screen should also get scaled when the keyboard pops up? But then, how much? To make up for the space taken by the keyboard - can we get that? To fit the screen?
* This needs testing on tablets. I added 018c099cc72c7ad99df7dd12f7cd5b396807c839 because tablet experience was suboptimal, let's compare the different approaches on tablets.

**Comment by gujjwal00** [comment]
>Me thinks we are using immersive (sticky) mode: 

Yes, but we are also setting these flags:
https://github.com/bk138/multivnc/blob/408e2becda40375b4a538980d7c47fc49fbfeee8/android/app/src/main/java/com/coboltforge/dontmind/multivnc/VncCanvasActivity.java#L561-L563

These seems to enable *more strict* fullscreen mode. So far I have found three modes:

1. Truly fullscreen:
    - Currently in use
    - Specified by `LayoutParams.FLAG_FULLSCREEN` on window 
    - Android ignore any request to auto resize (by `adjustResize`)
    - We don't get any information about keyboard visibility. (have to watch layout events)

2. Immersive/Immersive_Sticky
   - Enabled by `View.SYSTEM_UI_FLAG_*` 
   - 'Looks' same as fullscreen
   - It gets disabled if FabMenu is shown or Dialog pops up.
   -  `adjustResize` is still ignored
   - We get 'window insets' when keyboard is visible so we can use that

3. Non-fullscreen mode
   -  `adjustResize` works  

>This needs testing on tablets. I added 018c099 because tablet experience was suboptimal, let's compare the different approaches on tablets.

Yeah, there seems to be a lot of edge cases around fullscreen+resize in Android.

**Comment by bk138** [comment]
I'll have a tablet at hand soon to test this.

**Pull request closed without merging**
