### PR TITLE
Corrections for Spanish and added translations to Galician and Catalan

### PR DESCRIPTION
**Pull request by susobaco**

### CODE REVIEW

**Comment by bk138** [comment]
¡Muchissimas gracias! Can you please re-push the PR with commit messages that go like "Android: add xyz translation"? Then we're good to go!

**Review by bk138 — CHANGES_REQUESTED** [review]
¡Muchissimas gracias! Can you please re-push the PR with commit messages that go like "Android: add xyz translation"? Then we're good to go!

**Comment by bk138** [comment]
I've now added 2539cc5377302a268bdd1952b823aeb5ab574efc, 5fe4441144ce0f175534d71811641b0bb2b2c6b6 and 0d4893441ec6c27b0874f363c978641bbba105c1. Muchas gracias por su contribucion!

Some notes:
* You can update a PR without opening a new one with a reset and then force-push, see https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request :-)
* https://chris.beams.io/posts/git-commit/ has a very nice writeup on commit messages :-)

**Comment by susobaco** [comment]
Thank you and sorry, I don't have much experience yet.

**Pull request closed without merging**
